### ISSUE TITLE
Error when making a POST request with vertx

### ISSUE THREAD

**Issue by JonaCaste** [confluentinc/parallel-consumer#600] opened 2023-07-08 01:34 UTC
I need to create a POST request with vertx,  following the example "parallel-consumer-example-vertx" I created a "webClient" to later invoke "parallelConsumer.vertxHttpRequestStream". But at the moment of sending a Json as body, the flow of the application breaks; because the POST request is done infinitely because the commit to the kafka queue record is not done.

Code fragment in method "run()":
```
this.parallelConsumer = JStreamVertxParallelStreamProcessor.createEosStreamProcessor(options);
parallelConsumer.subscribe(of(inputTopic));

Stream resultStream = parallelConsumer.vertxHttpRequestStream((webClient, rec) -> {
            
            System.out.println("Msg recibido");
            
            ConsumerRecord consumerRecord = rec.getSingleConsumerRecord();
            
            Map<String, String> params = new HashMap();

            JsonObject payload = new JsonObject(consumerRecord.value().toString());
            System.out.println("Payload" + payload);
            
            RequestInfo reqInf = new RequestInfo("localhost", port, "/send-message", params);

            HttpRequest<Buffer> req = (HttpRequest<Buffer>) webClient.post(reqInf.getPort(), reqInf.getHost(), reqInf.getContextPath());
                   /* Error */
                   /* 
                    .sendJsonObject(new JsonObject("{\"hola\":\"mundo\"}"));
                    .onSuccess(res -> {
                        System.out.println(res.bodyAsString());
                    });
                   */

            return req;
});
```
Thank you for your help

**Comment by MishaTsypkin** [comment] 2023-08-31 16:06
I'm having the same problem.

It seems that it is impossible to send a request body by design.
[According to the implementation](https://github.com/confluentinc/parallel-consumer/blob/master/parallel-consumer-vertx/src/main/java/io/confluent/parallelconsumer/vertx/VertxParallelEoSStreamProcessor.java#L151C11-L151C12):
```
 HttpRequest<Buffer> call = carefullyRun(webClientRequestFunction, webClient, record);

  Future<HttpResponse<Buffer>> send = call.send(); 
```
`HttpRequest::send` is always called without parameters, but it seems to be the only way to transfer body data into a request, [according to the Vert.x docs](https://vertx.io/docs/apidocs/io/vertx/ext/web/client/HttpRequest.html).
The only way to transfer data is through query params via `HttpRequest::addQueryParams`.

@astubbs @rkolesnev could you please confirm that this is the case and maybe explain the reasoning behind such limitation?

Thanks!

**Comment by MishaTsypkin** [comment] 2023-08-31 16:27
@JonaCaste on a second look it seems that we can fix our problem by using `JStreamVertxParallelStreamProcessor::vertxHttpWebClientStream` instead of `JStreamVertxParallelStreamProcessor::vertxHttpRequestStream`.

So for your example, switching:
```
Stream resultStream = parallelConsumer.vertxHttpRequestStream((webClient, rec) -> {
```
to
```
Stream resultStream = parallelConsumer.vertxHttpWebClientStream((webClient, rec) -> {
```

Might do the trick :)

**Comment by rkolesnev** [comment] 2023-09-01 16:43
To be honest i think its just additional overload - for simple requests (like GET etc) - vertxHttpRequestStream can be used, for other operations - vertxHttpWebClientStream can be used and so forth. 

Closing the issue.

**Closed by rkolesnev** 2023-09-01 16:43 UTC
