### ISSUE TITLE
Parallel consumer stops processing data sometimes

### ISSUE THREAD

**Issue by bdeneuter** [confluentinc/parallel-consumer#606] opened 2023-07-19 13:58 UTC
Hi,

In production we noticed that the parallel consumer (0.5.2.5) sometimes stops processing data. It is a similar problem like https://github.com/confluentinc/parallel-consumer/issues/547.
We can not reproduce the problem but we noticed the following:

- the number of fetches goes to 0 or close to 0
- a restart fixes the problem

When looking into the fix for 547, I was wondering if the fix is complete?
The fix validates if a WorkContainer is stale and end the flight of the WorkContainer and changes `numberRecordsOutForProcessing`
https://github.com/confluentinc/parallel-consumer/blob/master/parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/WorkManager.java#L251

Are those WorkContainers also cleaned up from the ProcessingShard which keeps a set of WorkContainers and is used to fetch work?
https://github.com/confluentinc/parallel-consumer/blob/master/parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/ProcessingShard.java#L44

For the succes and failure case, the ShardManager is being called while for the stale case the ShardManager is not called:
https://github.com/confluentinc/parallel-consumer/blob/master/parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/WorkManager.java#L152
https://github.com/confluentinc/parallel-consumer/blob/master/parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/WorkManager.java#L173

Kind regards,
Bart

**Comment by johnbyrnejb** [comment] 2023-07-25 09:06
We will investigate but we are planning to release a new version this week which will include metrics. Can you upgrade your version at that point and see if you can capture any more information that may be useful to triage? 

Thanks

**Comment by bdeneuter** [comment] 2023-07-25 09:44
Looking forward for the new version. Metrics would definitely help us to investigate this.

**Comment by krvajal** [comment] 2023-07-31 15:33
I am experiencing the same issue. Looking forward to the metrics update

**Comment by acktsap** [comment] 2023-08-06 09:32
Hi, i also experiencing the same issue..

**Comment by sangreal** [comment] 2023-08-07 06:56
I also experience this issue and after some digging I find the root cause, I am trying to fix this on my end, maybe will create a PR for this later.

**Comment by 10000-ki** [comment] 2023-08-07 09:42
Hi, i also experiencing the same issue too..

**Comment by eddyv** [comment] 2023-08-25 16:39
Closed by #623

**Closed by eddyv** 2023-08-25 16:39 UTC
