### ISSUE TITLE
Support Kafka-clients:3.7.0

### ISSUE THREAD

**Issue by dumontxiong** [confluentinc/parallel-consumer#775] opened 2024-05-29 05:21 UTC
Hi team
io.confluent.parallelconsumer:parallel-consumer-core:0.2.5.8 not support Kafka-clients:3.7.0
Cause AbstractParallelEoSStreamProcessor.checkAutoCommitIsDisabled row 265 :
Field coordinatorField = consumer.getClass().getDeclaredField("coordinator") will throw NoSuchFieldException.
The RCA is KafkaConsumer（3.6.0） is very different with  KafkaConsumer（3.7.0）,KafkaConsumer（3.7.0） doesn't contain coordinator and other fields
BRs,
Dumont

**Comment by nscuro** [comment] 2024-05-29 09:48
Duplicate of #721, fixed in #762.

**Closed** 2024-05-29 09:50 UTC
