### ISSUE TITLE
Slow produce with pollAndProduce with many output messages

### ISSUE THREAD

**Issue by birdayz** [confluentinc/parallel-consumer#297] opened 2022-05-12 07:26 UTC
Hi! First off, thanks for this great library.

When using pollAndProduce, a synchronous produce is done by calling get() on the future. This is done in a tight loop for each message, i.e. PC consumes one message, and wants to send 700+ messages as result. For each of the 700 msgs, produce is done, and get() is called on the future.
See here:

Inside the loop, the future/get(): https://github.com/confluentinc/parallel-consumer/blob/7b389d1272d83d96098a3d1c07836ec957a2acb4/parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/ProducerManager.java#L146 

The loop itself:
https://github.com/confluentinc/parallel-consumer/blob/7b389d1272d83d96098a3d1c07836ec957a2acb4/parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/ParallelEoSStreamProcessor.java#L69

This is EXTREMELY slow for large fan-outs. For small fan-outs, or 1:1 consume/produce, i think it is not as much of an issue.

I propose to add a function processMany, which will first produce all records, gathers a list of futures, and then, after all are produced, waits for them. This should be much faster, because all records are produced async,i.e. producing "the next record" does not have to wait for the previous record to be acked.

Would you be open for a patch here? I'm happy to submit one.

**Comment by astubbs** [comment] 2022-05-12 12:29
Duplicate of:
- #232

But let's continue discussion in #297 as you've already proposed a solution here :)

**Closed** 2022-05-17 11:02 UTC
Labels: enhancement, good first issue, high, performance
